apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: todo-app

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      serviceAccountName: backend-sa

      containers:
        - name: backend

          image: gaffar08/todo-backend:v1.0.124-ada557e

          imagePullPolicy: Always

          ports:
            - containerPort: 5000

          envFrom:
            - configMapRef:
                name: backend-config

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"

            limits:
              memory: "256Mi"
              cpu: "200m"

          livenessProbe:
            httpGet:
              path: /health
              port: 5000

            initialDelaySeconds: 15
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: 5000

            initialDelaySeconds: 5
            periodSeconds: 5
